services:
  database:
    container_name: rrc-mysql
    image: mysql:8.2.0
    networks:
      - rrc-default
    volumes:
      - rrc-mysql-data:/var/lib/mysql
      - rrc-mysql-conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 33306:3306
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  rrc-default:
    driver: bridge
    name: rrc-default

volumes:
  rrc-mysql-data:
    name: rrc-mysql-data
  rrc-mysql-conf:
    name: rrc-mysql-conf
